FORMAT: 1A
HOST: http://localhost:4007

# Alarm API
This API Blueprint represents the alarms api and mock server spec.

NOTE: This document is a **work in progress**.

# Group Alarm

:[Alarm](includes/alarm.md)

:[Alarms](includes/alarms.md)
